update scripted pipeline

diff --git a/scripted/Jenkinsfile b/scripted/Jenkinsfile
--- a/scripted/Jenkinsfile
+++ b/scripted/Jenkinsfile
@@ -1,24 +1,25 @@
-node('zip-job-docker') {
-  try {
-    
-    def zipJobImage = 'zip_job_image:latest'
-    def gitVars
+timestamps{
 
-    stage('Checkout') {
+  node('zip-job-docker') {
+    try {
+      def zipJobImage = 'zip_job_image:latest'
+      def gitVars
+      def artifactoryID = 'artifactory-tlv'
+      stage('Checkout') {
         gitVars = checkout scm
         echo "repo cloned ${gitVars.GIT_URL}"
         sh 'ls -la'
-    }
-    stage('Build') {
-        docker.image(zipJobImage).inside {
+      }
+      stage('Build') {
+          docker.image(zipJobImage).inside {
             echo "Successfully running inside the container!"
             sh 'python3 zip_job.py'
             sh 'ls -la'
-        }
-    }
-    stage('Publish') {
+          }
+      }
+      stage('Publish') {
         sh 'ls -la'
-        def server = Artifactory.server('artifactory-tlv')
+        def server = Artifactory.server(artifactoryID)
         def uploadSpec = """{
           "files": [
             {
@@ -28,14 +29,14 @@ node('zip-job-docker') {
           ]
         }"""
         server.upload(uploadSpec)
-    }
-  } catch (err) {
-      echo "Build failed: ${err}"
-      currentBuild.result = 'FAILURE'
-  } finally {
+      }
+    } catch (err) {
+        echo "Build failed: ${err}"
+        currentBuild.result = 'FAILURE'
+    } finally {
     stage('Cleanup') {
-        deleteDir()
-        sh 'rm -rf "${WORKSPACE}@tmp"'
+      deleteDir()
+      sh 'rm -rf "${WORKSPACE}@tmp" || true'
     }
   }
 }
